# Clicks a specified location in a specified direction and types string (or performs specified click action) and optionally returns copied string
#
#
#  Parameter:
#
#		(1) inputFieldLabelOrXY: input field label or XY coordinate (can specify with "text" at the beginning if image with same name exists)
#
#		(2) typeString:
#				(a) string to be typed into the input field
#				(b) can also be a click action: 'click', 'doubleclick', 'tripleclick')
#
#		(3)	direction: specify direction of input field from label (e.g., right, down, xy)
#
#		(4 to 10) param4 to param10 are optional in no specific order:
#
#			- offset (must begin with "offset" followed by number, offset75): specify number of pixels to offset by to click inside the input field
#			- index (should be just a number from -10 to 10): specify only if there are multiple instances of the same word on the screen
#
#			- search rectangle (must begins with "screen" or "sr(", screenBL or sr(radiusc,100)): sets searchRectangle
#			- valid characters (must contain "char"): sets validCharacters to "*"
#			- ignore newline (must contain "line"): sets ignoreNewline to true
#			- text difference (must contain "diff" followed by number, textDiff3 or diff2): sets textDifference to specified number
#			- invert image (must have "invert", invert): sets invertImage to true
#			- dpi (must begin with "dpi" followed by number, dpi144): specify if OCR tuning is required
#			- waitFor (must begin with "wait" followed by number, wait10): specify number of seconds to waitFor (default is 7)
#
#
#  Usage Syntax:
#
#		clicktype "Username","GuestQA",right
#		clicktype "Username","GuestQA",down,dpi144,offset20
#		set confirmationNumber to clicktype("Confirmation Number",tripleclick,down,dpi85,-1)
#
#
# SUITE DESCR:  Jerry's Utilities (Sensetalk Toolkit, Established Since 2020)
# SUITE  NAME:  jtils
# SCRIPT NAME:  clicktype.script
# AUTHOR NAME:  Jerry Park
#


params inputFieldLabelOrXY, typeString, direction, param4, param5, param6, param7, param8, param9, param10
log "./clicktype.script"

# set the things
set (index,offset) to (1,15)
repeat for each item of [param4, param5, param6, param7]
	if it is empty then exit repeat
	if it...
		...begins with "wai": set pList.waitFor to (the match of <max digits> in it).text
		...begins with "dpi": set pList.dpi to (the match of <max digits> in it).text
		...contains "inv": set pList.invertImage to true
		...contains "char": set pList.validCharacters to "*"
		...contains "line": set pList.ignoreNewline to true
		...contains "diff": set pList.textDifference to (the match of <max digits> in it).text
		...begins with "ind": set index to (the match of <max digits> in it).text
		...begins with "off": set offset to (the match of <max digits> in it).text
		...begins with "screen": set pList.searchRectangle to sr(it)
		...begins with "sr(": set pList.searchRectangle to sr(item 1 of split(item 2 of split(it,"sr("),")"))
		else:
			if it is in -10..10 then set index to it //when param does not begin with "index" due to negative number such as last instance or -1
	end if
end repeat

# determine offset based on whether the input field is right of or below the label
if direction contains "d" then set (position,offset) to (bottomCenter,[0,offset])\
		else if direction contains "r" then set (position,offset) to (rightCenter,[offset+5,0])\
			else if direction does not contain <"r" or "d"> then set (position,offset) to (rightCenter,[offset+5,0])  //backwards compatibility for when right was default direction

# formulate based on coordinate or text
if inputFieldLabelOrXY is a list then set (inputField,pList) to (inputFieldLabelOrXY+offset,"[x,y]") else set pList.text to inputFieldLabelOrXY

# adding context to the execution log for debugging
log !"  [[notSign]] clicked [[direction]] from [[pList]]"
if typeString is not contained by ["tripleclick","doubleclick","click"]\
		then log !"  [[notSign]] typing '[[typeString]]'"\
		else log !"  [[notSign]] [[typeString]]ing in the input field"

# determine click location from text with offset considering if index was specified if not a direct [x,y] location
if pList is a property list
	if index is 1\
			then set inputField to imageRectangle(pList).(position)+offset\
			else set inputField to (item index of everyImageRectangle(pList)).(position)+offset
end if

# perform the specified type or click action
if typeString is...
	"click": click inputField
	"doubleclick": doubleclick inputField
	"tripleclick": tripleclick inputField
	else:
		click inputField
		wait 0.99
		typeText typeString
		exit handler
end if

# if double or tripleclick is specified, returns the selected value
if typeString is contained by ["doubleclick","tripleclick"]
	key.copy
	return remoteClipboard()
end if



