# Contains handlers that are modularized to be used across the jtils project.
#
#
# SUITE DESCR:  Jerry's Utilities (Sensetalk Toolkit, Established Since 2020)
# SUITE  NAME:  jtils
# SCRIPT NAME:  common.script
# AUTHOR NAME:  Jerry Park
#


to imageOrText sourceAndProperties
	# determines whether the passed in parameter is an image or text string and returns the properly constructed property list
	
	# set the thing
	set source to item 1 of sourceAndProperties
	
	# handling backwards compatibility - explicitly specifying text as source for when image with same name existing might be a concern
	if source begins with "text" considering case then return {text:trimStart(item -1 of split(source,chars 1..4 of source))}
	
	# if text was not explicitly specified for source, determine if text or image
	set ocrParameters to items 2..-1 of sourceAndProperties
	if ocrParameters.asText contains pattern "(case|new|aggress|dpi|char|word|invert|space|under|multi)"
		return {text:source}
	else
		try
			if imageInfo(source) > "" then return {image:source} //checking for image
		catch
			return {text:source} //if no image, falling back to text
		end try
	end if
end to imageOrText



