# Waits for image or text for a specified duration or until the image or text disappears from the screen including an option to wait afterwards
#
# Eggplant's built-in "wait until" can theoretically continue to execute forever if what it is looking for isn't found
# Another problem with the built-in wait until function is that execution can continue with the next line of code too soon which can cause execution failure
#
# This script can also replace the built-in "waitFor" function as a more robust alternative
#
#
#  Parameter:
#
#		(1) duration: number of seconds
#		(2) imageOrText: image name or text (can explicitly specify text by leading with 'text' for when image exists with same name)
#		(3) notFound: found or not found
#		(4) waitAfter (should begin with "wait"): number of seconds after found or not found in case of unstable environments
#		(5) searchRec: search rectangle (supported by the sr.script)
#		(6) dpi (should begin with "dpi"): dpi value for OCR
#
#
#  Usage Syntax:
#
#		waitUntil 10,"browser/refresh",found
#		waitUntil 30,"Save Print Output As",found,waitAfter10
#		waitUntil 30,"Save Print Output As",notFound,waitAfter0,screenBR
#		waitUntil 30,"Save Print Output As",notFound,waitAfter1,sr(radius,tll,100),dpi85
#
#
# SUITE DESCR:  Jerry's Utilities (Sensetalk Toolkit, Established Since 2020)
# SUITE  NAME:  jtils
# SCRIPT NAME:  waitUntil.script
# AUTHOR NAME:  Jerry Park
#


params duration=9.99, imageOrText, notFound="found", waitAfter=wait0, searchRec="", dpi=dpi72

if notFound contains "not" then set expected to "not found" else set expected to "found"
log !"./waitUntil.script [[notSign]] waiting [[duration]] seconds for '[[imageOrText]]' to be [[expected ]]..."
set visible to empty
set timeExpired to false
logger 0

# determining whether to look for image or text
set pList to common.imageOrText(imageOrText)

# add searchRectangle, DPI, and waitFor properties to the property list
if searchRec begins with "sr("\
		then set pList.searchRectangle to sr(item 1 of split(item 2 of split(searchRec,"sr("),")"))\
		else if searchRec > ""\
			then set pList.searchRectangle to sr(searchRec)
if pList.text > "" and if dpi begins with "dpi"\
		then set pList.dpi to (the match of <max digits> in dpi).text\
		else set pList.dpi to dpi //backwards compatible when dpi param was not specified as "dpi" before the value
set pList.waitFor to 0.99
--log pList

# looking for imageOrText to be found (or be removed from) the screen for the specified duration of time
repeat for duration seconds
	if notFound contains "not" and if not imageFound(pList)\
			then set visible to false\
			else if notFound is "found" and if imageFound(pList)\
				then set visible to true
	if visible > "" then exit repeat
end repeat
sr
if notFound contains "not" and visible is empty then set timeExpired to true

# log result for waitUntil
if...
	timeExpired:
		logger
		screenshot !"waitUntil - still visible when wait time expired" //debug
		note logWarning,"waitUntil",!<<"[[imageOrText]]" was still on screen when specified duration of [[duration]] seconds had expired>>,"script"
	notFound is "found" and not visible:
		logger
		screenshot !"waitUntil - not found within [[duration]] seconds" //debug
		note logWarning,"waitUntil",!<<"[[imageOrText]]" was not found within [[duration]] seconds>>,"script"
	notFound is "found" and visible:
		logger
		note log,"waitUntil",!<<Found "[[imageOrText]]" at [[foundImageLocation()]]!>>,"script"
	notFound contains "not" and visible is not false:
		logger
		screenshot !"waitUntil - still visible after specified duration" //debug
		note logWarning,"waitUntil",!<<"[[imageOrText]]" is still visible after specified duration>>,"script"
	notFound contains "not":
		logger
		note log,"waitUntil",!<<"[[imageOrText]]" is no longer visible on the screen!>>,"script"
end if

# handles wait time after found/notFound if specified
if waitAfter begins with "wait"\
		then set waitAfter to (the match of <max digits> in waitAfter).text //backwards compatible when waitAfer param was not specified as "wait" before the value
if waitAfter > 0
	log !<<          [[notSign]] Waiting after for [[waitAfter]] seconds...>>
	wait waitAfter
	log !<<          [[notSign]] Done!>>
end if



